In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data_pup.csv')
df.head()

,participant,trial,session,ip_label,bin,gaze_x,gaze_y,blink,saccade,in_central_ia,...,AoA_reading_English,English_Use,Home_entropy,School_entropy,Work_entropy,Free_time_entropy,Hobbies_entropy,All_entropy,Percent_Use_entropy,identification_Spanish
0,02karval,4,1,target,-25,974.13,531.92,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
1,02karval,4,1,target,-24,972.28,533.13,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
2,02karval,4,1,target,-23,972.48,531.24,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
3,02karval,4,1,target,-22,973.16,528.65,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
4,02karval,4,1,target,-21,972.85,528.84,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0